services:
  frontend:
    build: ./frontend
    container_name: app_frontend_finance
    restart: always
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes:
      - ./frontend/src:/app-frontend/src

  backend:
    container_name: app_backend_finance
    build: ./backend
    ports:
      - 5000:5000
    platform: linux/x86_64
    working_dir: /app-backend
    restart: always
    command: dev
    volumes:
      - ./backend/src:/app-backend/src

    environment:
      - JWT_SECRET=jwt_secret
      - MYSQL_USER=root
      - MYSQL_PASSWORD=flp5660
      - MYSQL_DATABASE=flp-finance
      - MYSQL_HOST=db
      - PORT=5000
    depends_on:
      - db

  db:
    container_name: app_database
    image: mysql:5.7
    platform: linux/x86_64
    command: --max_allowed_packet=32M
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=flp5660
      - MYSQL_DATABASE=flp-finance
    volumes:
      - flp-finance:/var/lib/mysql

volumes:
  flp-finance:
